name: Pyright

on: [pull_request, workflow_dispatch]

jobs:
  flake8_linting:
    runs-on: ubuntu-latest
    name: Pyright
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.x
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: pyright
        uses: jakebailey/pyright-action@v3
        with:
            version: PATH
